"""empty message

Revision ID: ebf601e10502
Revises: 
Create Date: 2024-02-12 23:33:39.235708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf601e10502'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female'), nullable=False),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_result',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('time_finished', sa.Time(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('difficulty_level_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('in progress', 'finished'), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['quiz_categories.category_id'], ),
    sa.ForeignKeyConstraint(['difficulty_level_id'], ['difficulty_level.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('option1', sa.String(length=255), nullable=False),
    sa.Column('option2', sa.String(length=255), nullable=False),
    sa.Column('option3', sa.String(length=255), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('correct_answer_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['quiz_categories.category_id'], ),
    sa.ForeignKeyConstraint(['correct_answer_id'], ['correct_answer.correct_answer_id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question_bank.qb_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transaction',
    sa.Column('transaction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.payment_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    with op.batch_alter_table('correct_answer', schema=None) as batch_op:
        batch_op.drop_constraint('correct_answer_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('correct_answer_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'question_bank', ['question_id'], ['qb_id'])
        batch_op.create_foreign_key(None, 'quiz_categories', ['cat_id'], ['category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correct_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('correct_answer_ibfk_1', 'question_bank', ['question_id'], ['qb_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key('correct_answer_ibfk_2', 'quiz_categories', ['cat_id'], ['category_id'], onupdate='CASCADE', ondelete='CASCADE')

    op.drop_table('transaction')
    op.drop_table('question_answer')
    op.drop_table('quiz_result')
    op.drop_table('admin')
    # ### end Alembic commands ###
